config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit update ]
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :description, :genre, :published_year, :author_name, :author_bio)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit update ]
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.book, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:user_id, :body, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_book.html.erb
<%= link_to book, class: "block" do %>
<div class="transition-colors duration-300 transform bg-gray-300 hover:bg-brand-gray-light-hover dark:bg-brand-gray-light dark:hover:bg-gray-700 p-6 rounded-lg min-h-full">
  <div class="w-7/12 mb-10">
    <% if book.id.odd? %>
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 460 460" style="enable-background:new 0 0 460 460;" xml:space="preserve" width="170" height="170">
      <g id="XMLID_844_">
        <path id="XMLID_1068_" style="fill:#695538;" d="M110,435H60l-10-30h70L110,435z M410,405h-70l10,30h50L410,405z"/>
        <path id="XMLID_843_" style="fill:#CBB57A;" d="M460,415H0v-40h460V415z"/>
        <path id="XMLID_842_" style="fill:#9E8E60;" d="M460,425H0v-20h460V425z"/>
        <path id="XMLID_1783_" style="fill:#D66A40;" d="M200,105v280c0,5.523-4.477,10-10,10h-50c-5.523,0-10-4.477-10-10   c0,5.523-4.477,10-10,10H70c-5.523,0-10-4.477-10-10V35c0-5.523,4.477-10,10-10h50c5.523,0,10,4.477,10,10v70   c0-5.523,4.477-10,10-10h50C195.523,95,200,99.477,200,105z M419.751,350.584L259.15,121.222   c-3.168-4.524-9.403-5.624-13.927-2.456l-40.958,28.679c-4.524,3.168-5.624,9.403-2.456,13.927l160.601,229.363   c3.168,4.524,9.403,5.624,13.927,2.456l40.958-28.679C421.82,361.344,422.919,355.109,419.751,350.584z"/>
        <path id="XMLID_1778_" style="fill:#B14724;" d="M200,235H60V135h140V235z M200,295H60v30h140V295z"/>
        <path id="XMLID_1782_" style="fill:#732D21;" d="M259.15,121.222l160.601,229.363c3.168,4.524,2.068,10.759-2.456,13.927   l-40.958,28.679c-4.524,3.168-10.759,2.068-13.927-2.456L201.809,161.372c-3.168-4.524-2.068-10.76,2.456-13.927l40.958-28.679   C249.747,115.598,255.982,116.698,259.15,121.222z"/>
        <path id="XMLID_1781_" style="fill:#C18F2B;" d="M287.829,162.18l-57.341,40.15l-17.207-24.575l57.341-40.15L287.829,162.18z    M310.772,194.946l-57.341,40.15l74.565,106.49l57.341-40.15L310.772,194.946z"/>
        <path id="XMLID_1780_" style="fill:#64757C;" d="M130,35v350c0,5.523-4.477,10-10,10H70c-5.523,0-10-4.477-10-10V35   c0-5.523,4.477-10,10-10h50C125.523,25,130,29.477,130,35z"/>
        <path id="XMLID_1779_" style="fill:#374145;" d="M130,295H60V145h70V295z M130,95H60v20h70V95z M130,325H60v20h70V325z"/>
      </g>
      </svg>
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" width="150" height="150" viewBox="0 0 181.111 203.866" class="mt-5">
        <g id="Group_28" data-name="Group 28" transform="translate(-501 -184.407)">
          <path id="Subtraction_1" data-name="Subtraction 1" d="M185.446,39.845H25V37.319c5.552-3.4,9-10,9-17.21S30.552,6.3,25,2.9V0H185.678a20.594,20.594,0,0,1,14.483,5.8,19.566,19.566,0,0,1,5.95,14.12,20.11,20.11,0,0,1-6.153,14.122A20.735,20.735,0,0,1,185.446,39.845Z" transform="translate(476 346.391)" fill="#e6e9ee"/>
          <g id="Group_27" data-name="Group 27" transform="translate(54 85)">
            <g id="Group_25" data-name="Group 25" transform="translate(447 259.354)">
              <path id="Path_9" data-name="Path 9" d="M94.917,361.164H253.841a17.433,17.433,0,1,0,0-34.864H94.917v-4.528H253.841a21.961,21.961,0,1,1,0,43.919H94.917Z" transform="translate(-94.917 -321.773)" fill="#d36c46"/>
              <g id="Group_1" data-name="Group 1" transform="translate(79.853 7.018)">
                <path id="Path_2" data-name="Path 2" d="M241.034,336.246h90.329c-.227-.453-.68-.679-1.132-1.132h0l-1.132-1.132H241.034Z" transform="translate(-241.034 -333.982)" fill="#acb3ba"/>
                <path id="Path_3" data-name="Path 3" d="M241.034,344.123H334.08c-.227-.453-.453-.679-.453-1.132h0c-.226-.453-.453-.679-.679-1.132H241.034Z" transform="translate(-241.034 -337.331)" fill="#acb3ba"/>
                <path id="Path_4" data-name="Path 4" d="M241.034,352.394h94.63c0-.453-.227-.68-.227-1.132h-.226c0-.453-.227-.679-.227-1.132H241.034Z" transform="translate(-241.034 -340.848)" fill="#acb3ba"/>
                <path id="Path_5" data-name="Path 5" d="M241.034,360.271h94.857v-1.132h0v-1.132H241.034Z" transform="translate(-241.034 -344.197)" fill="#acb3ba"/>
                <path id="Path_6" data-name="Path 6" d="M241.034,368.148h93.951c0-.453.226-.679.226-1.132h0c0-.453.226-.679.226-1.132h-94.4Z" transform="translate(-241.034 -347.546)" fill="#acb3ba"/>
                <path id="Path_7" data-name="Path 7" d="M241.034,376.418h91.914c.226-.453.453-.679.679-1.132h0c.226-.453.453-.68.453-1.132H241.034Z" transform="translate(-241.034 -351.063)" fill="#acb3ba"/>
                <path id="Path_8" data-name="Path 8" d="M241.034,384.295H329.1c.453-.453.905-.679,1.132-1.132h0l1.132-1.132H241.034Z" transform="translate(-241.034 -354.412)" fill="#acb3ba"/>
              </g>
            </g>
            <g id="Group_24" data-name="Group 24" transform="translate(447 210.228)">
              <path id="Path_10" data-name="Path 10" d="M277.534,242.511c-.227-.905-.679-1.585,0-2.264H118.157a19.7,19.7,0,1,0,0,39.392h159.6c-.679-.679-.453-1.132,0-2.264A29.558,29.558,0,0,1,277.534,242.511Z" transform="translate(-97.73 -237.983)" fill="#e6e9ee"/>
              <path id="Path_11" data-name="Path 11" d="M276.2,275.7H117.5a17.433,17.433,0,1,1,0-34.864H276.422v-4.528H117.5a21.961,21.961,0,1,0,0,43.919H276.422V275.7Z" transform="translate(-95.311 -236.308)" fill="#2d92a1"/>
              <g id="Group_2" data-name="Group 2" transform="translate(62.121 9.282)">
                <path id="Path_12" data-name="Path 12" d="M235.126,252.455v5.433h95.989a26.516,26.516,0,0,1,2.038-5.433H235.126Z" transform="translate(-218.374 -252.455)" fill="#acb3ba"/>
                <path id="Path_13" data-name="Path 13" d="M268.6,275.218h75.84a21.806,21.806,0,0,1,0-5.433H268.6Z" transform="translate(-232.608 -259.823)" fill="#acb3ba"/>
                <path id="Path_14" data-name="Path 14" d="M205.982,292.547H320.761a53.168,53.168,0,0,1-2.038-5.433H205.982Z" transform="translate(-205.982 -267.192)" fill="#acb3ba"/>
              </g>
            </g>
            <g id="Group_26" data-name="Group 26" transform="translate(-5)">
              <rect id="Rectangle_14" data-name="Rectangle 14" width="26.155" height="110.825" transform="translate(473 99.407)" fill="#67baeb"/>
              <rect id="Rectangle_15" data-name="Rectangle 15" width="26.155" height="110.825" transform="translate(542.023 99.407)" fill="#f44533"/>
              <path id="Path_27" data-name="Path 27" d="M1017.2,451.521h26.155V340.7h-4.424V446.5H1017.2Z" transform="translate(-475.177 -241.293)" fill="#de3226"/>
              <rect id="Rectangle_16" data-name="Rectangle 16" width="21.465" height="103.204" transform="translate(499.155 107.025)" fill="#f4c23f"/>
              <path id="Path_28" data-name="Path 28" d="M548.556,426.8v83.543A15.858,15.858,0,0,1,532.7,526.2h0V530h21.465V426.8Z" transform="translate(-33.545 -319.775)" fill="#f4a93f"/>
              <rect id="Rectangle_17" data-name="Rectangle 17" width="21.465" height="96.395" transform="translate(520.558 113.838)" fill="#d1d5db"/>
              <path id="Path_29" data-name="Path 29" d="M791.951,503.8v75.641A17.351,17.351,0,0,1,774.6,596.792h0v3.4h21.465V503.8Z" transform="translate(-254.042 -389.962)" fill="#b2b5ba"/>
              <rect id="Rectangle_18" data-name="Rectangle 18" width="26.155" height="7.706" transform="translate(473 116.882)" fill="#4d4c78"/>
              <rect id="Rectangle_19" data-name="Rectangle 19" width="26.155" height="7.706" transform="translate(473 185.055)" fill="#4d4c78"/>
              <rect id="Rectangle_20" data-name="Rectangle 20" width="5.371" height="74.956" transform="translate(506.711 122.385)" fill="#f4a93f"/>
              <path id="Path_30" data-name="Path 30" d="M832.567,642.439h-9.7a1.77,1.77,0,0,1,0-3.539h9.7a1.77,1.77,0,0,1,0,3.539Z" transform="translate(-296.428 -513.109)" fill="#797b80"/>
              <path id="Path_31" data-name="Path 31" d="M832.567,743.739h-9.7a1.77,1.77,0,0,1,0-3.539h9.7a1.77,1.77,0,0,1,0,3.539Z" transform="translate(-296.428 -605.446)" fill="#797b80"/>
              <path id="Path_32" data-name="Path 32" d="M832.567,844.939h-9.7a1.77,1.77,0,1,1,0-3.539h9.7a1.77,1.77,0,1,1,0,3.539Z" transform="translate(-296.428 -697.691)" fill="#797b80"/>
              <path id="Path_33" data-name="Path 33" d="M848.04,1452.139h-6.37a1.77,1.77,0,1,1,0-3.539h6.37a1.77,1.77,0,1,1,0,3.539Z" transform="translate(-313.565 -1251.167)" fill="#797b80"/>
              <path id="Path_34" data-name="Path 34" d="M1092.07,609.224a1.778,1.778,0,0,1-1.77-1.77V534.07a1.77,1.77,0,1,1,3.539,0v73.385A1.77,1.77,0,0,1,1092.07,609.224Z" transform="translate(-541.809 -415.94)" fill="#b11a31"/>
              <path id="Path_35" data-name="Path 35" d="M1201.37,609.224a1.77,1.77,0,0,1-1.77-1.77V534.07a1.77,1.77,0,1,1,3.539,0v73.385a1.778,1.778,0,0,1-1.77,1.77Z" transform="translate(-641.438 -415.94)" fill="#b11a31"/>
              <path id="Path_39" data-name="Path 39" d="M255.7,427.286V340.7h7.556V451.521H237.1v-5.636h0A18.6,18.6,0,0,0,255.7,427.286Z" transform="translate(235.9 -241.293)" fill="#323150" opacity="0.1"/>
              <rect id="Rectangle_22" data-name="Rectangle 22" width="5.733" height="46.431" rx="2.867" transform="translate(473 133.029)" fill="#83d0fb"/>
              <g id="Group_23" data-name="Group 23" transform="translate(0 1)">
                <rect id="Rectangle_13" data-name="Rectangle 13" width="24.182" height="102.474" transform="translate(570.74 108.345) rotate(-10)" fill="#67baeb"/>
                <path id="Path_36" data-name="Path 36" d="M1540.81,1382.3h0l-23.81,4.22.619,3.486,23.81-4.22Z" transform="translate(-930.755 -1190.733)" fill="#4d4c78"/>
                <rect id="Rectangle_21" data-name="Rectangle 21" width="24.182" height="3.539" transform="translate(572.481 118.226) rotate(-10)" fill="#4d4c78"/>
                <path id="Path_37" data-name="Path 37" d="M1430.429,758.777h0l-.619-3.477h0L1406,759.512h0l.619,3.486h0Z" transform="translate(-829.576 -619.209)" fill="#4d4c78"/>
                <path id="Path_38" data-name="Path 38" d="M1497.038,1135.286l-.619-3.486-23.819,4.22.619,3.486h0Z" transform="translate(-890.283 -962.397)" fill="#4d4c78"/>
                <path id="Path_40" data-name="Path 40" d="M1541.36,393l-6.061,1.079,14.042,79.349a17.236,17.236,0,0,1-13.98,19.988l-.761.142.805,4.565,23.819-4.212Z" transform="translate(-946.798 -288.966)" fill="#323150" opacity="0.1"/>
                <g id="Group_6" data-name="Group 6" transform="translate(574.652 127.786)" opacity="0.2">
                  <rect id="Rectangle_23" data-name="Rectangle 23" width="6.388" height="51.68" rx="3.194" transform="translate(0 1.109) rotate(-10)" fill="#fff"/>
                  <path id="Path_41" data-name="Path 41" d="M1402.563,716.622a3.238,3.238,0,0,1-3.185-2.681l-7.892-44.6a3.239,3.239,0,1,1,6.379-1.124l7.892,44.6a3.238,3.238,0,0,1-2.619,3.751h0A3.157,3.157,0,0,1,1402.563,716.622Zm-7.892-50.991a2.95,2.95,0,0,0-.549.053,3.132,3.132,0,0,0-2.539,3.645l7.893,44.594a3.14,3.14,0,1,0,6.185-1.088l-7.892-44.6A3.15,3.15,0,0,0,1394.67,665.631Z" transform="translate(-1390.951 -665.174)" fill="#231f20"/>
                </g>
              </g>
              <rect id="Rectangle_24" data-name="Rectangle 24" width="5.733" height="11.852" rx="2.867" transform="translate(473 102.07)" fill="#83d0fb"/>
              <rect id="Rectangle_25" data-name="Rectangle 25" width="4.3" height="51.892" rx="2.15" transform="translate(499.155 108.803)" fill="#fad564"/>
              <rect id="Rectangle_26" data-name="Rectangle 26" width="4.114" height="29.35" rx="2.057" transform="translate(520.558 153.105)" fill="#e1e4e8"/>
              <rect id="Rectangle_27" data-name="Rectangle 27" width="10.733" height="5.055" rx="2.527" transform="translate(520.558 113.838)" fill="#e1e4e8"/>
              <rect id="Rectangle_28" data-name="Rectangle 28" width="3.442" height="66.816" rx="1.721" transform="translate(542.023 113.838)" fill="#f46253"/>
            </g>
          </g>
        </g>
      </svg>
    <% end %>
  </div>
  <h3 class="tracking-widest text-brand-orange uppercase text-xs font-bold title-font mb-2">
    <%= book.genre %></h3>
  <h2 class="text-2xl title-font mb-4 font-serif font-semibold">
    <%= book.name %></h2>
  <p class="leading-relaxed text-gray-600 dark:text-gray-400 text-base mb-8"> <%= book.description.truncate(150) %> </p>
  <p class="leading-relaxed text-sm text-gray-600 dark:text-gray-400 text-base ml-auto mr-0"><span class="text-brand-orange"> <%= book.author_name %> </span> — published <%= book.published_year %>.</p>
</div>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "contents") do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :published_year %>
    <%= form.number_field :published_year, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author_name %>
    <%= form.text_field :author_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author_bio %>
    <%= form.text_area :author_bio, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing book</h1>

  <%= render "form", book: @book %>

  <%= link_to "Show this book", @book, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: review, class: "contents") do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :book_id %>
    <%= form.text_field :book_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= review.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= review.body %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Book:</strong>
    <%= review.book_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this review", review, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this review', edit_review_path(review), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing review</h1>

  <%= render "form", review: @review %>

  <%= link_to "Show this review", @review, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to reviews", reviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reviews/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reviews</h1>
    <%= link_to 'New review', new_review_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="reviews" class="min-w-full">
    <%= render @reviews %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New review</h1>

  <%= render "form", review: @review %>

  <%= link_to 'Back to reviews', reviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/reviews/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @review %>

    <%= link_to 'Edit this review', edit_review_path(@review), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this review', review_path(@review), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to reviews', reviews_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>